// flow-typed signature: e244f993a25643cb7becd5ee4906e171
// flow-typed version: <<STUB>>/xstate_v^4.3.2/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'xstate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'xstate' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'xstate/dist/xstate.graph' {
  declare module.exports: any;
}

declare module 'xstate/dist/xstate.interpreter' {
  declare module.exports: any;
}

declare module 'xstate/dist/xstate' {
  declare module.exports: any;
}

declare module 'xstate/dist/xstate.utils' {
  declare module.exports: any;
}

declare module 'xstate/es/actions' {
  declare module.exports: any;
}

declare module 'xstate/es/actionTypes' {
  declare module.exports: any;
}

declare module 'xstate/es/constants' {
  declare module.exports: any;
}

declare module 'xstate/es/graph' {
  declare module.exports: any;
}

declare module 'xstate/es/index' {
  declare module.exports: any;
}

declare module 'xstate/es/interpreter' {
  declare module.exports: any;
}

declare module 'xstate/es/invoke' {
  declare module.exports: any;
}

declare module 'xstate/es/Machine' {
  declare module.exports: any;
}

declare module 'xstate/es/mapState' {
  declare module.exports: any;
}

declare module 'xstate/es/match' {
  declare module.exports: any;
}

declare module 'xstate/es/matchesState' {
  declare module.exports: any;
}

declare module 'xstate/es/patterns' {
  declare module.exports: any;
}

declare module 'xstate/es/scxml' {
  declare module.exports: any;
}

declare module 'xstate/es/State' {
  declare module.exports: any;
}

declare module 'xstate/es/StateNode' {
  declare module.exports: any;
}

declare module 'xstate/es/StateTree' {
  declare module.exports: any;
}

declare module 'xstate/es/test' {
  declare module.exports: any;
}

declare module 'xstate/es/types' {
  declare module.exports: any;
}

declare module 'xstate/es/utils' {
  declare module.exports: any;
}

declare module 'xstate/lib/actions' {
  declare module.exports: any;
}

declare module 'xstate/lib/actionTypes' {
  declare module.exports: any;
}

declare module 'xstate/lib/constants' {
  declare module.exports: any;
}

declare module 'xstate/lib/graph' {
  declare module.exports: any;
}

declare module 'xstate/lib/history' {
  declare module.exports: any;
}

declare module 'xstate/lib/index' {
  declare module.exports: any;
}

declare module 'xstate/lib/interpreter' {
  declare module.exports: any;
}

declare module 'xstate/lib/invoke' {
  declare module.exports: any;
}

declare module 'xstate/lib/Machine' {
  declare module.exports: any;
}

declare module 'xstate/lib/mapState' {
  declare module.exports: any;
}

declare module 'xstate/lib/match' {
  declare module.exports: any;
}

declare module 'xstate/lib/matchesState' {
  declare module.exports: any;
}

declare module 'xstate/lib/patterns' {
  declare module.exports: any;
}

declare module 'xstate/lib/scxml' {
  declare module.exports: any;
}

declare module 'xstate/lib/src/actions' {
  declare module.exports: any;
}

declare module 'xstate/lib/src/actionTypes' {
  declare module.exports: any;
}

declare module 'xstate/lib/src/constants' {
  declare module.exports: any;
}

declare module 'xstate/lib/src/graph' {
  declare module.exports: any;
}

declare module 'xstate/lib/src/index' {
  declare module.exports: any;
}

declare module 'xstate/lib/src/interpreter' {
  declare module.exports: any;
}

declare module 'xstate/lib/src/invoke' {
  declare module.exports: any;
}

declare module 'xstate/lib/src/Machine' {
  declare module.exports: any;
}

declare module 'xstate/lib/src/mapState' {
  declare module.exports: any;
}

declare module 'xstate/lib/src/patterns' {
  declare module.exports: any;
}

declare module 'xstate/lib/src/scxml' {
  declare module.exports: any;
}

declare module 'xstate/lib/src/State' {
  declare module.exports: any;
}

declare module 'xstate/lib/src/StateNode' {
  declare module.exports: any;
}

declare module 'xstate/lib/src/StateTree' {
  declare module.exports: any;
}

declare module 'xstate/lib/src/types' {
  declare module.exports: any;
}

declare module 'xstate/lib/src/utils' {
  declare module.exports: any;
}

declare module 'xstate/lib/State' {
  declare module.exports: any;
}

declare module 'xstate/lib/StateNode' {
  declare module.exports: any;
}

declare module 'xstate/lib/StateTree' {
  declare module.exports: any;
}

declare module 'xstate/lib/test' {
  declare module.exports: any;
}

declare module 'xstate/lib/test/actionCreators.test' {
  declare module.exports: any;
}

declare module 'xstate/lib/test/actions.test' {
  declare module.exports: any;
}

declare module 'xstate/lib/test/activities.test' {
  declare module.exports: any;
}

declare module 'xstate/lib/test/after.test' {
  declare module.exports: any;
}

declare module 'xstate/lib/test/assign.test' {
  declare module.exports: any;
}

declare module 'xstate/lib/test/deep.test' {
  declare module.exports: any;
}

declare module 'xstate/lib/test/deterministic.test' {
  declare module.exports: any;
}

declare module 'xstate/lib/test/examples/6.16.test' {
  declare module.exports: any;
}

declare module 'xstate/lib/test/examples/6.17.test' {
  declare module.exports: any;
}

declare module 'xstate/lib/test/examples/6.6.test' {
  declare module.exports: any;
}

declare module 'xstate/lib/test/examples/6.8.test' {
  declare module.exports: any;
}

declare module 'xstate/lib/test/examples/6.9.test' {
  declare module.exports: any;
}

declare module 'xstate/lib/test/examples/cd.test' {
  declare module.exports: any;
}

declare module 'xstate/lib/test/final.test' {
  declare module.exports: any;
}

declare module 'xstate/lib/test/fixtures/factorial' {
  declare module.exports: any;
}

declare module 'xstate/lib/test/fixtures/id' {
  declare module.exports: any;
}

declare module 'xstate/lib/test/fixtures/omni' {
  declare module.exports: any;
}

declare module 'xstate/lib/test/graph.test' {
  declare module.exports: any;
}

declare module 'xstate/lib/test/guards.test' {
  declare module.exports: any;
}

declare module 'xstate/lib/test/history.test' {
  declare module.exports: any;
}

declare module 'xstate/lib/test/id.test' {
  declare module.exports: any;
}

declare module 'xstate/lib/test/initial.test' {
  declare module.exports: any;
}

declare module 'xstate/lib/test/internalTransitions.test' {
  declare module.exports: any;
}

declare module 'xstate/lib/test/interpreter.test' {
  declare module.exports: any;
}

declare module 'xstate/lib/test/invalid.test' {
  declare module.exports: any;
}

declare module 'xstate/lib/test/invoke.test' {
  declare module.exports: any;
}

declare module 'xstate/lib/test/machine.test' {
  declare module.exports: any;
}

declare module 'xstate/lib/test/mapState.test' {
  declare module.exports: any;
}

declare module 'xstate/lib/test/matchesState.test' {
  declare module.exports: any;
}

declare module 'xstate/lib/test/meta.test' {
  declare module.exports: any;
}

declare module 'xstate/lib/test/multiple.test' {
  declare module.exports: any;
}

declare module 'xstate/lib/test/parallel.test' {
  declare module.exports: any;
}

declare module 'xstate/lib/test/patterns.test' {
  declare module.exports: any;
}

declare module 'xstate/lib/test/resolve.test' {
  declare module.exports: any;
}

declare module 'xstate/lib/test/scxml.test' {
  declare module.exports: any;
}

declare module 'xstate/lib/test/state.test' {
  declare module.exports: any;
}

declare module 'xstate/lib/test/stateIn.test' {
  declare module.exports: any;
}

declare module 'xstate/lib/test/stateTree.test' {
  declare module.exports: any;
}

declare module 'xstate/lib/test/strict.test' {
  declare module.exports: any;
}

declare module 'xstate/lib/test/transient.test' {
  declare module.exports: any;
}

declare module 'xstate/lib/test/types.test' {
  declare module.exports: any;
}

declare module 'xstate/lib/test/utils' {
  declare module.exports: any;
}

declare module 'xstate/lib/types' {
  declare module.exports: any;
}

declare module 'xstate/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'xstate/dist/xstate.graph.js' {
  declare module.exports: $Exports<'xstate/dist/xstate.graph'>;
}
declare module 'xstate/dist/xstate.interpreter.js' {
  declare module.exports: $Exports<'xstate/dist/xstate.interpreter'>;
}
declare module 'xstate/dist/xstate.js' {
  declare module.exports: $Exports<'xstate/dist/xstate'>;
}
declare module 'xstate/dist/xstate.utils.js' {
  declare module.exports: $Exports<'xstate/dist/xstate.utils'>;
}
declare module 'xstate/es/actions.js' {
  declare module.exports: $Exports<'xstate/es/actions'>;
}
declare module 'xstate/es/actionTypes.js' {
  declare module.exports: $Exports<'xstate/es/actionTypes'>;
}
declare module 'xstate/es/constants.js' {
  declare module.exports: $Exports<'xstate/es/constants'>;
}
declare module 'xstate/es/graph.js' {
  declare module.exports: $Exports<'xstate/es/graph'>;
}
declare module 'xstate/es/index.js' {
  declare module.exports: $Exports<'xstate/es/index'>;
}
declare module 'xstate/es/interpreter.js' {
  declare module.exports: $Exports<'xstate/es/interpreter'>;
}
declare module 'xstate/es/invoke.js' {
  declare module.exports: $Exports<'xstate/es/invoke'>;
}
declare module 'xstate/es/Machine.js' {
  declare module.exports: $Exports<'xstate/es/Machine'>;
}
declare module 'xstate/es/mapState.js' {
  declare module.exports: $Exports<'xstate/es/mapState'>;
}
declare module 'xstate/es/match.js' {
  declare module.exports: $Exports<'xstate/es/match'>;
}
declare module 'xstate/es/matchesState.js' {
  declare module.exports: $Exports<'xstate/es/matchesState'>;
}
declare module 'xstate/es/patterns.js' {
  declare module.exports: $Exports<'xstate/es/patterns'>;
}
declare module 'xstate/es/scxml.js' {
  declare module.exports: $Exports<'xstate/es/scxml'>;
}
declare module 'xstate/es/State.js' {
  declare module.exports: $Exports<'xstate/es/State'>;
}
declare module 'xstate/es/StateNode.js' {
  declare module.exports: $Exports<'xstate/es/StateNode'>;
}
declare module 'xstate/es/StateTree.js' {
  declare module.exports: $Exports<'xstate/es/StateTree'>;
}
declare module 'xstate/es/test.js' {
  declare module.exports: $Exports<'xstate/es/test'>;
}
declare module 'xstate/es/types.js' {
  declare module.exports: $Exports<'xstate/es/types'>;
}
declare module 'xstate/es/utils.js' {
  declare module.exports: $Exports<'xstate/es/utils'>;
}
declare module 'xstate/lib/actions.js' {
  declare module.exports: $Exports<'xstate/lib/actions'>;
}
declare module 'xstate/lib/actionTypes.js' {
  declare module.exports: $Exports<'xstate/lib/actionTypes'>;
}
declare module 'xstate/lib/constants.js' {
  declare module.exports: $Exports<'xstate/lib/constants'>;
}
declare module 'xstate/lib/graph.js' {
  declare module.exports: $Exports<'xstate/lib/graph'>;
}
declare module 'xstate/lib/history.js' {
  declare module.exports: $Exports<'xstate/lib/history'>;
}
declare module 'xstate/lib/index.js' {
  declare module.exports: $Exports<'xstate/lib/index'>;
}
declare module 'xstate/lib/interpreter.js' {
  declare module.exports: $Exports<'xstate/lib/interpreter'>;
}
declare module 'xstate/lib/invoke.js' {
  declare module.exports: $Exports<'xstate/lib/invoke'>;
}
declare module 'xstate/lib/Machine.js' {
  declare module.exports: $Exports<'xstate/lib/Machine'>;
}
declare module 'xstate/lib/mapState.js' {
  declare module.exports: $Exports<'xstate/lib/mapState'>;
}
declare module 'xstate/lib/match.js' {
  declare module.exports: $Exports<'xstate/lib/match'>;
}
declare module 'xstate/lib/matchesState.js' {
  declare module.exports: $Exports<'xstate/lib/matchesState'>;
}
declare module 'xstate/lib/patterns.js' {
  declare module.exports: $Exports<'xstate/lib/patterns'>;
}
declare module 'xstate/lib/scxml.js' {
  declare module.exports: $Exports<'xstate/lib/scxml'>;
}
declare module 'xstate/lib/src/actions.js' {
  declare module.exports: $Exports<'xstate/lib/src/actions'>;
}
declare module 'xstate/lib/src/actionTypes.js' {
  declare module.exports: $Exports<'xstate/lib/src/actionTypes'>;
}
declare module 'xstate/lib/src/constants.js' {
  declare module.exports: $Exports<'xstate/lib/src/constants'>;
}
declare module 'xstate/lib/src/graph.js' {
  declare module.exports: $Exports<'xstate/lib/src/graph'>;
}
declare module 'xstate/lib/src/index.js' {
  declare module.exports: $Exports<'xstate/lib/src/index'>;
}
declare module 'xstate/lib/src/interpreter.js' {
  declare module.exports: $Exports<'xstate/lib/src/interpreter'>;
}
declare module 'xstate/lib/src/invoke.js' {
  declare module.exports: $Exports<'xstate/lib/src/invoke'>;
}
declare module 'xstate/lib/src/Machine.js' {
  declare module.exports: $Exports<'xstate/lib/src/Machine'>;
}
declare module 'xstate/lib/src/mapState.js' {
  declare module.exports: $Exports<'xstate/lib/src/mapState'>;
}
declare module 'xstate/lib/src/patterns.js' {
  declare module.exports: $Exports<'xstate/lib/src/patterns'>;
}
declare module 'xstate/lib/src/scxml.js' {
  declare module.exports: $Exports<'xstate/lib/src/scxml'>;
}
declare module 'xstate/lib/src/State.js' {
  declare module.exports: $Exports<'xstate/lib/src/State'>;
}
declare module 'xstate/lib/src/StateNode.js' {
  declare module.exports: $Exports<'xstate/lib/src/StateNode'>;
}
declare module 'xstate/lib/src/StateTree.js' {
  declare module.exports: $Exports<'xstate/lib/src/StateTree'>;
}
declare module 'xstate/lib/src/types.js' {
  declare module.exports: $Exports<'xstate/lib/src/types'>;
}
declare module 'xstate/lib/src/utils.js' {
  declare module.exports: $Exports<'xstate/lib/src/utils'>;
}
declare module 'xstate/lib/State.js' {
  declare module.exports: $Exports<'xstate/lib/State'>;
}
declare module 'xstate/lib/StateNode.js' {
  declare module.exports: $Exports<'xstate/lib/StateNode'>;
}
declare module 'xstate/lib/StateTree.js' {
  declare module.exports: $Exports<'xstate/lib/StateTree'>;
}
declare module 'xstate/lib/test.js' {
  declare module.exports: $Exports<'xstate/lib/test'>;
}
declare module 'xstate/lib/test/actionCreators.test.js' {
  declare module.exports: $Exports<'xstate/lib/test/actionCreators.test'>;
}
declare module 'xstate/lib/test/actions.test.js' {
  declare module.exports: $Exports<'xstate/lib/test/actions.test'>;
}
declare module 'xstate/lib/test/activities.test.js' {
  declare module.exports: $Exports<'xstate/lib/test/activities.test'>;
}
declare module 'xstate/lib/test/after.test.js' {
  declare module.exports: $Exports<'xstate/lib/test/after.test'>;
}
declare module 'xstate/lib/test/assign.test.js' {
  declare module.exports: $Exports<'xstate/lib/test/assign.test'>;
}
declare module 'xstate/lib/test/deep.test.js' {
  declare module.exports: $Exports<'xstate/lib/test/deep.test'>;
}
declare module 'xstate/lib/test/deterministic.test.js' {
  declare module.exports: $Exports<'xstate/lib/test/deterministic.test'>;
}
declare module 'xstate/lib/test/examples/6.16.test.js' {
  declare module.exports: $Exports<'xstate/lib/test/examples/6.16.test'>;
}
declare module 'xstate/lib/test/examples/6.17.test.js' {
  declare module.exports: $Exports<'xstate/lib/test/examples/6.17.test'>;
}
declare module 'xstate/lib/test/examples/6.6.test.js' {
  declare module.exports: $Exports<'xstate/lib/test/examples/6.6.test'>;
}
declare module 'xstate/lib/test/examples/6.8.test.js' {
  declare module.exports: $Exports<'xstate/lib/test/examples/6.8.test'>;
}
declare module 'xstate/lib/test/examples/6.9.test.js' {
  declare module.exports: $Exports<'xstate/lib/test/examples/6.9.test'>;
}
declare module 'xstate/lib/test/examples/cd.test.js' {
  declare module.exports: $Exports<'xstate/lib/test/examples/cd.test'>;
}
declare module 'xstate/lib/test/final.test.js' {
  declare module.exports: $Exports<'xstate/lib/test/final.test'>;
}
declare module 'xstate/lib/test/fixtures/factorial.js' {
  declare module.exports: $Exports<'xstate/lib/test/fixtures/factorial'>;
}
declare module 'xstate/lib/test/fixtures/id.js' {
  declare module.exports: $Exports<'xstate/lib/test/fixtures/id'>;
}
declare module 'xstate/lib/test/fixtures/omni.js' {
  declare module.exports: $Exports<'xstate/lib/test/fixtures/omni'>;
}
declare module 'xstate/lib/test/graph.test.js' {
  declare module.exports: $Exports<'xstate/lib/test/graph.test'>;
}
declare module 'xstate/lib/test/guards.test.js' {
  declare module.exports: $Exports<'xstate/lib/test/guards.test'>;
}
declare module 'xstate/lib/test/history.test.js' {
  declare module.exports: $Exports<'xstate/lib/test/history.test'>;
}
declare module 'xstate/lib/test/id.test.js' {
  declare module.exports: $Exports<'xstate/lib/test/id.test'>;
}
declare module 'xstate/lib/test/initial.test.js' {
  declare module.exports: $Exports<'xstate/lib/test/initial.test'>;
}
declare module 'xstate/lib/test/internalTransitions.test.js' {
  declare module.exports: $Exports<'xstate/lib/test/internalTransitions.test'>;
}
declare module 'xstate/lib/test/interpreter.test.js' {
  declare module.exports: $Exports<'xstate/lib/test/interpreter.test'>;
}
declare module 'xstate/lib/test/invalid.test.js' {
  declare module.exports: $Exports<'xstate/lib/test/invalid.test'>;
}
declare module 'xstate/lib/test/invoke.test.js' {
  declare module.exports: $Exports<'xstate/lib/test/invoke.test'>;
}
declare module 'xstate/lib/test/machine.test.js' {
  declare module.exports: $Exports<'xstate/lib/test/machine.test'>;
}
declare module 'xstate/lib/test/mapState.test.js' {
  declare module.exports: $Exports<'xstate/lib/test/mapState.test'>;
}
declare module 'xstate/lib/test/matchesState.test.js' {
  declare module.exports: $Exports<'xstate/lib/test/matchesState.test'>;
}
declare module 'xstate/lib/test/meta.test.js' {
  declare module.exports: $Exports<'xstate/lib/test/meta.test'>;
}
declare module 'xstate/lib/test/multiple.test.js' {
  declare module.exports: $Exports<'xstate/lib/test/multiple.test'>;
}
declare module 'xstate/lib/test/parallel.test.js' {
  declare module.exports: $Exports<'xstate/lib/test/parallel.test'>;
}
declare module 'xstate/lib/test/patterns.test.js' {
  declare module.exports: $Exports<'xstate/lib/test/patterns.test'>;
}
declare module 'xstate/lib/test/resolve.test.js' {
  declare module.exports: $Exports<'xstate/lib/test/resolve.test'>;
}
declare module 'xstate/lib/test/scxml.test.js' {
  declare module.exports: $Exports<'xstate/lib/test/scxml.test'>;
}
declare module 'xstate/lib/test/state.test.js' {
  declare module.exports: $Exports<'xstate/lib/test/state.test'>;
}
declare module 'xstate/lib/test/stateIn.test.js' {
  declare module.exports: $Exports<'xstate/lib/test/stateIn.test'>;
}
declare module 'xstate/lib/test/stateTree.test.js' {
  declare module.exports: $Exports<'xstate/lib/test/stateTree.test'>;
}
declare module 'xstate/lib/test/strict.test.js' {
  declare module.exports: $Exports<'xstate/lib/test/strict.test'>;
}
declare module 'xstate/lib/test/transient.test.js' {
  declare module.exports: $Exports<'xstate/lib/test/transient.test'>;
}
declare module 'xstate/lib/test/types.test.js' {
  declare module.exports: $Exports<'xstate/lib/test/types.test'>;
}
declare module 'xstate/lib/test/utils.js' {
  declare module.exports: $Exports<'xstate/lib/test/utils'>;
}
declare module 'xstate/lib/types.js' {
  declare module.exports: $Exports<'xstate/lib/types'>;
}
declare module 'xstate/lib/utils.js' {
  declare module.exports: $Exports<'xstate/lib/utils'>;
}
